import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { PropsWithChildren } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="absolute py-20 w-full flex justify-center ">
          <Link className="" href={"/"}>
            Home
          </Link>
        </header>
        <div className="min-h-screen flex flex-col items-center justify-center max-w-screen-lg mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
