import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./common/header";
import "./globals.css";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="min-h-screen flex flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
